// Code generated by injector. DO NOT EDIT.

package main

import (
	config "github.com/mickamy/injector/example/config"
	infra "github.com/mickamy/injector/example/infra"
	service "github.com/mickamy/injector/example/service"
)

// NewContainer initializes dependencies and constructs Container.
func NewContainer() *Container {
	readerDatabaseConfig := config.NewReaderDatabaseConfig()
	database := infra.NewDatabase(readerDatabaseConfig)
	user := service.NewUser(database)

	return &Container{
		Database:    database,
		UserService: user,
	}
}
