// Code generated by injector. DO NOT EDIT.

package main

import (
	di "github.com/mickamy/injector/example/embedded-error/di"
	service "github.com/mickamy/injector/example/embedded-error/service"
)

// NewApp initializes dependencies and constructs App.
func NewApp() (*App, error) {
	infra, err := di.NewInfra()
	if err != nil {
		return nil, err
	}
	user := service.NewUser(infra.Database)

	return &App{
		UserService: user,
	}, nil
}
