// Code generated by injector. DO NOT EDIT.

package main

import (
	di "github.com/mickamy/injector/example/embed/di"
	service "github.com/mickamy/injector/example/embed/service"
)

// NewApp initializes dependencies and constructs App.
func NewApp(infra *di.Infra) *App {
	database := infra.Database
	user := service.NewUser(database)

	return &App{
		UserService: user,
	}
}
