// Code generated by injector. DO NOT EDIT.

package di

import (
	config "github.com/mickamy/injector/example/embedded-error/config"
	infra "github.com/mickamy/injector/example/embedded-error/infra"
)

// NewInfra initializes dependencies and constructs Infra.
func NewInfra() (*Infra, error) {
	readerDatabaseConfig := config.NewReaderDatabaseConfig()
	database, err := infra.NewDatabase(readerDatabaseConfig)
	if err != nil {
		return nil, err
	}

	return &Infra{
		Database: database,
	}, nil
}
