// Code generated by injector. DO NOT EDIT.

package main

import (
	greeter "github.com/mickamy/injector/example/returns/greeter"
)

// NewApp initializes dependencies and constructs app.
func NewApp() greeter.Greeter {
	greeter := greeter.NewGreeter()

	return &app{
		service: greeter,
	}
}
