// Code generated by injector. DO NOT EDIT.

package main

import (
	greeter "github.com/mickamy/injector/example/returns/greeter"
)

// NewGreeter initializes dependencies and constructs app.
func NewGreeter() greeter.Greeter {
	service := greeter.NewGreeter()

	return &app{
		service: service,
	}
}
