package emit_test

import (
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"strings"
	"testing"

	"github.com/mickamy/injector/internal/diag"
	"github.com/mickamy/injector/internal/emit"
	"github.com/mickamy/injector/internal/ir"
	"github.com/mickamy/injector/internal/packages"
	"github.com/mickamy/injector/internal/plan"
	"github.com/mickamy/injector/internal/scan"
)

func TestEmit_SimpleChain(t *testing.T) {
	t.Parallel()

	src := `package myapp
type DB struct{}
type User struct{}
func NewDB() *DB { return nil }
func NewUser(db *DB) *User { return nil }
type Container struct {
	User *User ` + "`inject:\"\"`" + `
}
`
	p := buildPlan(t, src)

	got, err := emit.Emit("myapp", []plan.Plan{p})
	if err != nil {
		t.Fatalf("Emit: %v", err)
	}

	want := `// Code generated by injector. DO NOT EDIT.

package myapp

// NewContainer initializes dependencies and constructs Container.
func NewContainer() *Container {
	db := NewDB()
	user := NewUser(db)

	return &Container{
		User: user,
	}
}
`
	if string(got) != want {
		t.Errorf("output mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestEmit_WithError(t *testing.T) {
	t.Parallel()

	src := `package myapp
type DB struct{}
type User struct{}
func NewDB() (*DB, error) { return nil, nil }
func NewUser(db *DB) *User { return nil }
type Container struct {
	User *User ` + "`inject:\"\"`" + `
}
`
	p := buildPlan(t, src)

	got, err := emit.Emit("myapp", []plan.Plan{p})
	if err != nil {
		t.Fatalf("Emit: %v", err)
	}

	want := `// Code generated by injector. DO NOT EDIT.

package myapp

// NewContainer initializes dependencies and constructs Container.
func NewContainer() (*Container, error) {
	db, err := NewDB()
	if err != nil {
		return nil, err
	}
	user := NewUser(db)

	return &Container{
		User: user,
	}, nil
}
`
	if string(got) != want {
		t.Errorf("output mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestEmit_WithMustVariant(t *testing.T) {
	t.Parallel()

	src := `package myapp
type DB struct{}
func NewDB() (*DB, error) { return nil, nil }

//injector:container must
type Container struct {
	DB *DB ` + "`inject:\"\"`" + `
}
`
	p := buildPlan(t, src)

	got, err := emit.Emit("myapp", []plan.Plan{p})
	if err != nil {
		t.Fatalf("Emit: %v", err)
	}

	want := `// Code generated by injector. DO NOT EDIT.

package myapp

// NewContainer initializes dependencies and constructs Container.
func NewContainer() (*Container, error) {
	db, err := NewDB()
	if err != nil {
		return nil, err
	}

	return &Container{
		DB: db,
	}, nil
}

// MustNewContainer initializes dependencies and constructs Container or panics on failure.
func MustNewContainer() *Container {
	v, err := NewContainer()
	if err != nil {
		panic(err)
	}
	return v
}
`
	if string(got) != want {
		t.Errorf("output mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestEmit_WithArgInput(t *testing.T) {
	t.Parallel()

	src := `package myapp
type DB struct{}
type User struct{}
func NewUser(db *DB) *User { return nil }
type Container struct {
	_    *DB   ` + "`inject:\"arg\"`" + `
	User *User ` + "`inject:\"\"`" + `
}
`
	p := buildPlan(t, src)

	got, err := emit.Emit("myapp", []plan.Plan{p})
	if err != nil {
		t.Fatalf("Emit: %v", err)
	}

	want := `// Code generated by injector. DO NOT EDIT.

package myapp

// NewContainer initializes dependencies and constructs Container.
func NewContainer(db *DB) *Container {
	user := NewUser(db)

	return &Container{
		User: user,
	}
}
`
	if string(got) != want {
		t.Errorf("output mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestEmit_NilReturnTypeIsRejected(t *testing.T) {
	t.Parallel()

	src := `package myapp
type DB struct{}
func NewDB() *DB { return nil }
type Container struct {
	DB *DB ` + "`inject:\"\"`" + `
}
`
	p := buildPlan(t, src)
	p.ReturnType = nil // simulate the upstream "no return type" failure mode

	if _, err := emit.Emit("myapp", []plan.Plan{p}); err == nil {
		t.Fatal("Emit accepted plan with nil ReturnType")
	}
}

func TestEmit_NonNilableReturnUsesZeroValue(t *testing.T) {
	t.Parallel()

	// Return type = value struct (non-nilable). The provider chain must
	// include at least one (T, error) provider so writeSteps takes the
	// error branch and writes the zero-value return.
	src := `package myapp
type DB struct{}
type Bag struct{ DB *DB }
func NewDB() (*DB, error) { return nil, nil }
func NewBag(db *DB) Bag { return Bag{DB: db} }

//injector:container returns=Bag
type app struct {
	B Bag ` + "`inject:\"\"`" + `
}
`
	pkg := loadTestPackage(t, src)
	cs, dsC := scan.Containers([]*packages.Package{pkg})
	if diag.HasErrors(dsC) {
		t.Fatalf("scan.Containers: %v", dsC)
	}
	ps, dsP := scan.Providers([]*packages.Package{pkg})
	if diag.HasErrors(dsP) {
		t.Fatalf("scan.Providers: %v", dsP)
	}

	var target ir.Container
	for _, c := range cs {
		if c.StructName == "app" {
			target = c
			break
		}
	}
	idx := plan.NewIndex(ps)
	pl, dsB := plan.Build(target, idx, plan.Options{})
	if diag.HasErrors(dsB) {
		t.Fatalf("plan.Build: %v", dsB)
	}

	out, err := emit.Emit("myapp", []plan.Plan{pl})
	if err != nil {
		t.Fatalf("Emit: %v", err)
	}
	if !strings.Contains(string(out), "*new(Bag)") {
		t.Errorf("expected *new(Bag) zero-value return in error path, got:\n%s", out)
	}
}

func TestEmit_GeneratedCompiles(t *testing.T) {
	t.Parallel()

	src := `package myapp
type DB struct{}
type User struct{}
func NewDB() *DB { return nil }
func NewUser(db *DB) *User { return nil }
type Container struct {
	User *User ` + "`inject:\"\"`" + `
}
`
	p := buildPlan(t, src)
	out, err := emit.Emit("myapp", []plan.Plan{p})
	if err != nil {
		t.Fatalf("Emit: %v", err)
	}

	// Re-type-check the original source plus the generated file as a single
	// package to ensure the generated code is syntactically and semantically
	// valid Go.
	fset := token.NewFileSet()
	original, err := parser.ParseFile(fset, "myapp.go", src, parser.ParseComments)
	if err != nil {
		t.Fatalf("parse original: %v", err)
	}
	generated, err := parser.ParseFile(fset, "injector_gen.go", out, parser.ParseComments)
	if err != nil {
		t.Fatalf("parse generated: %v\n--- generated ---\n%s", err, out)
	}
	if _, err := (&types.Config{Importer: importer.Default()}).
		Check("myapp", fset, []*ast.File{original, generated}, nil); err != nil {
		t.Fatalf("type-check generated: %v\n--- generated ---\n%s", err, out)
	}
}

func TestEmit_Embed(t *testing.T) {
	t.Parallel()

	src := `package myapp
type DB struct{}
type Repo struct{}
type Infra struct{ DB *DB }
func NewRepo(db *DB) *Repo { return nil }
type Container struct {
	_    *Infra ` + "`inject:\"embed\"`" + `
	Repo *Repo  ` + "`inject:\"\"`" + `
}
`
	p := buildPlan(t, src)

	got, err := emit.Emit("myapp", []plan.Plan{p})
	if err != nil {
		t.Fatalf("Emit: %v", err)
	}

	want := `// Code generated by injector. DO NOT EDIT.

package myapp

// NewContainer initializes dependencies and constructs Container.
func NewContainer(infra *Infra) *Container {
	db := infra.DB
	repo := NewRepo(db)

	return &Container{
		Repo: repo,
	}
}
`
	if string(got) != want {
		t.Errorf("output mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}

	fset := token.NewFileSet()
	original, err := parser.ParseFile(fset, "myapp.go", src, parser.ParseComments)
	if err != nil {
		t.Fatalf("parse original: %v", err)
	}
	generated, err := parser.ParseFile(fset, "injector_gen.go", got, parser.ParseComments)
	if err != nil {
		t.Fatalf("parse generated: %v\n--- generated ---\n%s", err, got)
	}
	if _, err := (&types.Config{Importer: importer.Default()}).
		Check("myapp", fset, []*ast.File{original, generated}, nil); err != nil {
		t.Fatalf("type-check generated: %v\n--- generated ---\n%s", err, got)
	}
}

// buildPlan runs scan + plan on src and returns the plan for the
// "Container" struct. Tests in this file all use that conventional name and
// default plan options.
func buildPlan(t *testing.T, src string) plan.Plan {
	t.Helper()
	const containerName = "Container"
	pkg := loadTestPackage(t, src)

	cs, dsC := scan.Containers([]*packages.Package{pkg})
	if diag.HasErrors(dsC) {
		t.Fatalf("scan.Containers: %v", dsC)
	}
	ps, dsP := scan.Providers([]*packages.Package{pkg})
	if diag.HasErrors(dsP) {
		t.Fatalf("scan.Providers: %v", dsP)
	}

	var target ir.Container
	for _, c := range cs {
		if c.StructName == containerName {
			target = c
			break
		}
	}
	if target.StructName == "" {
		t.Fatalf("container %q not found", containerName)
	}

	idx := plan.NewIndex(ps)
	pl, dsB := plan.Build(target, idx, plan.Options{})
	if diag.HasErrors(dsB) {
		t.Fatalf("plan.Build: %v", dsB)
	}
	return pl
}

func loadTestPackage(t *testing.T, src string) *packages.Package {
	t.Helper()
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "test.go", src, parser.ParseComments)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	info := &types.Info{
		Types: make(map[ast.Expr]types.TypeAndValue),
		Defs:  make(map[*ast.Ident]types.Object),
		Uses:  make(map[*ast.Ident]types.Object),
	}
	pkg, err := (&types.Config{Importer: importer.Default()}).Check("myapp", fset, []*ast.File{f}, info)
	if err != nil {
		t.Fatalf("check: %v", err)
	}
	return &packages.Package{
		PkgPath:   "myapp",
		Name:      "myapp",
		Syntax:    []*ast.File{f},
		Types:     pkg,
		TypesInfo: info,
		Fset:      fset,
	}
}
