package emit

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"io"
	"strings"

	"github.com/mickamy/injector/internal/plan"
)

// Emit renders a single .go file containing constructors for all the given
// plans. All plans must belong to the same Go package; the rendered file is
// formatted with go/format before returning.
func Emit(packageName string, plans []plan.Plan) ([]byte, error) {
	if packageName == "" {
		return nil, errors.New("emit: package name is required")
	}
	if len(plans) == 0 {
		return nil, errors.New("emit: no plans to emit")
	}

	containerPkg := plans[0].Container.PkgPath
	for _, p := range plans[1:] {
		if p.Container.PkgPath != containerPkg {
			return nil, fmt.Errorf(
				"emit: plans span multiple packages: %s vs %s",
				containerPkg, p.Container.PkgPath,
			)
		}
	}

	im := New(containerPkg)
	for _, p := range plans {
		collectImports(im, p)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by injector. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", packageName)

	if entries := im.Sorted(); len(entries) > 0 {
		buf.WriteString("import (\n")
		for _, e := range entries {
			fmt.Fprintf(&buf, "\t%s %q\n", e.Alias, e.Path)
		}
		buf.WriteString(")\n\n")
	}

	for _, p := range plans {
		if err := writeContainer(&buf, im, p); err != nil {
			return buf.Bytes(), fmt.Errorf("emit %s: %w", p.ConstructorName, err)
		}
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("emit: gofmt: %w", err)
	}
	return src, nil
}

// collectImports records every package referenced by a plan in im.
func collectImports(im *Imports, p plan.Plan) {
	if p.ReturnType != nil {
		im.AddType(p.ReturnType)
	}
	for _, in := range p.Inputs {
		im.AddType(in.Type)
	}
	for _, s := range p.Steps {
		if s.OutType != nil {
			im.AddType(s.OutType)
		}
		if s.Kind == plan.StepKindProvider && s.Provider != nil {
			im.AddProvider(s.Provider)
			for _, pt := range s.Provider.Params {
				im.AddType(pt)
			}
		}
	}
}

// writeContainer emits the constructor (and optional Must variant) for one plan.
func writeContainer(w io.Writer, im *Imports, p plan.Plan) error {
	name := p.ConstructorName
	structName := p.Container.StructName
	paramSig := formatParams(im, p.Inputs)
	retSig := im.QualifyType(p.ReturnType)

	fmt.Fprintf(w, "// %s initializes dependencies and constructs %s.\n", name, structName)
	if p.ReturnsError {
		fmt.Fprintf(w, "func %s(%s) (%s, error) {\n", name, paramSig, retSig)
	} else {
		fmt.Fprintf(w, "func %s(%s) %s {\n", name, paramSig, retSig)
	}

	if err := writeSteps(w, im, p); err != nil {
		return err
	}

	writeStructLiteral(w, p)
	if p.ReturnsError {
		fmt.Fprint(w, ", nil")
	}
	fmt.Fprint(w, "\n}\n\n")

	if p.EmitMust {
		writeMustVariant(w, im, p)
	}
	return nil
}

func writeSteps(w io.Writer, im *Imports, p plan.Plan) error {
	for _, s := range p.Steps {
		switch s.Kind {
		case plan.StepKindInput:
			// The input is already a function parameter — nothing to emit.
		case plan.StepKindProvider:
			if s.Provider == nil {
				return fmt.Errorf("provider step %q has nil Provider", s.VarName)
			}
			args := make([]string, 0, len(s.ArgSteps))
			for _, idx := range s.ArgSteps {
				args = append(args, p.Steps[idx].VarName)
			}
			call := im.QualifyProvider(s.Provider)
			if s.Provider.ReturnsError {
				fmt.Fprintf(w, "\t%s, err := %s(%s)\n", s.VarName, call, strings.Join(args, ", "))
				fmt.Fprint(w, "\tif err != nil {\n")
				fmt.Fprint(w, "\t\treturn nil, err\n")
				fmt.Fprint(w, "\t}\n")
			} else {
				fmt.Fprintf(w, "\t%s := %s(%s)\n", s.VarName, call, strings.Join(args, ", "))
			}
		}
	}
	return nil
}

func writeStructLiteral(w io.Writer, p plan.Plan) {
	fmt.Fprintf(w, "\n\treturn &%s{\n", p.Container.StructName)
	for _, o := range p.Outputs {
		v := p.Steps[o.StepIndex].VarName
		fmt.Fprintf(w, "\t\t%s: %s,\n", o.FieldName, v)
	}
	fmt.Fprint(w, "\t}")
}

// writeMustVariant emits MustNewX, which delegates to NewX and panics on
// error.
func writeMustVariant(w io.Writer, im *Imports, p plan.Plan) {
	name := "Must" + p.ConstructorName
	paramSig := formatParams(im, p.Inputs)
	retSig := im.QualifyType(p.ReturnType)

	fmt.Fprintf(w,
		"// %s initializes dependencies and constructs %s or panics on failure.\n",
		name, p.Container.StructName)
	fmt.Fprintf(w, "func %s(%s) %s {\n", name, paramSig, retSig)
	if p.ReturnsError {
		fmt.Fprintf(w, "\tv, err := %s(%s)\n", p.ConstructorName, formatArgs(p.Inputs))
		fmt.Fprint(w, "\tif err != nil {\n")
		fmt.Fprint(w, "\t\tpanic(err)\n")
		fmt.Fprint(w, "\t}\n")
		fmt.Fprint(w, "\treturn v\n")
	} else {
		fmt.Fprintf(w, "\treturn %s(%s)\n", p.ConstructorName, formatArgs(p.Inputs))
	}
	fmt.Fprint(w, "}\n\n")
}

func formatParams(im *Imports, inputs []plan.Input) string {
	if len(inputs) == 0 {
		return ""
	}
	parts := make([]string, 0, len(inputs))
	for _, in := range inputs {
		parts = append(parts, in.Name+" "+im.QualifyType(in.Type))
	}
	return strings.Join(parts, ", ")
}

func formatArgs(inputs []plan.Input) string {
	parts := make([]string, 0, len(inputs))
	for _, in := range inputs {
		parts = append(parts, in.Name)
	}
	return strings.Join(parts, ", ")
}
