// Code generated by injector. DO NOT EDIT.

package main

import (
	config "github.com/mickamy/injector/example/with-error/config"
	infra "github.com/mickamy/injector/example/with-error/infra"
	service "github.com/mickamy/injector/example/with-error/service"
)

// NewContainer initializes dependencies and constructs Container.
func NewContainer() (*Container, error) {
	readerDatabaseConfig := config.NewReaderDatabaseConfig()
	database, err := infra.NewDatabase(readerDatabaseConfig)
	if err != nil {
		return nil, err
	}
	user := service.NewUser(database)

	return &Container{
		Database:    database,
		UserService: user,
	}, nil
}
