// Code generated by injector. DO NOT EDIT.

package main

import (
	config "github.com/mickamy/injector/example/name-conflict/config"
	task2 "github.com/mickamy/injector/example/name-conflict/domain/task"
	user "github.com/mickamy/injector/example/name-conflict/domain/user"
	infra "github.com/mickamy/injector/example/name-conflict/infra"
)

// NewTaskContainer initializes dependencies and constructs TaskContainer.
func NewTaskContainer() *TaskContainer {
	writerDatabaseConfig := config.NewWriterDatabaseConfig()
	database := infra.NewDatabase(writerDatabaseConfig)
	repository := task2.NewRepository(database)
	repository2 := user.NewRepository(database)
	service := task2.NewService(repository, repository2)

	return &TaskContainer{
		Service: service,
	}
}

// NewUserContainer initializes dependencies and constructs UserContainer.
func NewUserContainer() *UserContainer {
	writerDatabaseConfig := config.NewWriterDatabaseConfig()
	database := infra.NewDatabase(writerDatabaseConfig)
	repository := user2.NewRepository(database)
	service := user2.NewService(repository)

	return &UserContainer{
		Service: service,
	}
}
