// Code generated by injector. DO NOT EDIT.

package main

import (
	config2 "github.com/mickamy/injector/example/name-conflict/config"
	task2 "github.com/mickamy/injector/example/name-conflict/domain/task"
	user3 "github.com/mickamy/injector/example/name-conflict/domain/user"
	infra2 "github.com/mickamy/injector/example/name-conflict/infra"
)

// NewTaskContainer initializes dependencies and constructs TaskContainer.
func NewTaskContainer() *TaskContainer {
	writerDatabaseConfig := config2.NewWriterDatabaseConfig()
	database := infra2.NewDatabase(writerDatabaseConfig)
	repository := task2.NewRepository(database)
	repository2 := user3.NewRepository(database)
	service := task2.NewService(repository, repository2)

	return &TaskContainer{
		Service: service,
	}
}

// NewUserContainer initializes dependencies and constructs UserContainer.
func NewUserContainer() *UserContainer {
	writerDatabaseConfig := config2.NewWriterDatabaseConfig()
	database := infra2.NewDatabase(writerDatabaseConfig)
	repository := user3.NewRepository(database)
	service := user3.NewService(repository)

	return &UserContainer{
		Service: service,
	}
}
