package scan_test

import (
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"testing"

	"github.com/mickamy/injector/internal/diag"
	"github.com/mickamy/injector/internal/ir"
	"github.com/mickamy/injector/internal/packages"
	"github.com/mickamy/injector/internal/scan"
)

func TestContainers_Smoke(t *testing.T) {
	t.Parallel()

	src := `package test

type DB struct{}
type User struct{}

type Container struct {
	User *User ` + "`inject:\"\"`" + `
}
`
	pkg := loadTestPackage(t, src)

	cs, ds := scan.Containers([]*packages.Package{pkg})
	if diag.HasErrors(ds) {
		t.Fatalf("unexpected error diags: %v", ds)
	}
	if len(cs) != 1 {
		t.Fatalf("got %d containers, want 1", len(cs))
	}
	c := cs[0]
	if c.StructName != "Container" {
		t.Errorf("StructName = %q", c.StructName)
	}
	if len(c.Fields) != 1 {
		t.Fatalf("fields = %d, want 1", len(c.Fields))
	}
	if got, want := c.Fields[0].Name, "User"; got != want {
		t.Errorf("field name = %q, want %q", got, want)
	}
	if c.Fields[0].Role != ir.RoleOut {
		t.Errorf("role = %v, want RoleOut", c.Fields[0].Role)
	}
}

func TestContainers_AllRolesAndDirective(t *testing.T) {
	t.Parallel()

	src := `package test

type Greeter interface{ Greet() string }
type DB struct{}

//injector:container name=NewApp must
type app struct {
	_   DB      ` + "`inject:\"with=NewWriter\"`" + `
	_   Greeter ` + "`inject:\"arg\"`" + `
	Foo Greeter ` + "`inject:\"returns\"`" + `
}
`
	pkg := loadTestPackage(t, src)
	cs, ds := scan.Containers([]*packages.Package{pkg})

	if diag.HasErrors(ds) {
		t.Fatalf("unexpected error diags: %v", ds)
	}
	if len(cs) != 1 {
		t.Fatalf("containers = %d, want 1", len(cs))
	}

	c := cs[0]
	if c.StructName != "app" {
		t.Errorf("StructName = %q", c.StructName)
	}
	if c.Directive.Name != "NewApp" {
		t.Errorf("Directive.Name = %q, want NewApp", c.Directive.Name)
	}
	if c.Directive.Must != ir.MustOn {
		t.Errorf("Directive.Must = %v, want MustOn", c.Directive.Must)
	}
	if len(c.Fields) != 3 {
		t.Fatalf("fields = %d, want 3", len(c.Fields))
	}

	roles := map[string]ir.Role{}
	hasReturns := map[string]bool{}
	for _, f := range c.Fields {
		roles[f.Name] = f.Role
		hasReturns[f.Name] = f.IsReturns
	}

	if roles["Foo"] != ir.RoleOut {
		t.Errorf("Foo role = %v, want RoleOut", roles["Foo"])
	}
	if !hasReturns["Foo"] {
		t.Errorf("Foo IsReturns = false, want true")
	}

	var argSeen, overrideSeen bool
	for _, f := range c.Fields {
		if f.Name != "_" {
			continue
		}
		switch f.Role {
		case ir.RoleArg:
			argSeen = true
		case ir.RoleOverride:
			overrideSeen = true
			if f.ProviderRef.Raw != "NewWriter" {
				t.Errorf("override ProviderRef = %q, want NewWriter", f.ProviderRef.Raw)
			}
		case ir.RoleOut, ir.RoleReturnsOnly, ir.RoleEmbed:
			// not relevant for this assertion
		}
	}
	if !argSeen {
		t.Errorf("RoleArg blank field not found")
	}
	if !overrideSeen {
		t.Errorf("RoleOverride blank field not found")
	}
}

func TestContainers_EmbedRole(t *testing.T) {
	t.Parallel()

	src := `package test

type Infra struct{}

type Container struct {
	_   *Infra ` + "`inject:\"embed\"`" + `
}
`
	pkg := loadTestPackage(t, src)
	cs, ds := scan.Containers([]*packages.Package{pkg})
	if diag.HasErrors(ds) {
		t.Fatalf("unexpected error diags: %v", ds)
	}
	if len(cs) != 1 || len(cs[0].Fields) != 1 {
		t.Fatalf("containers/fields shape unexpected: %+v", cs)
	}
	f := cs[0].Fields[0]
	if f.Role != ir.RoleEmbed {
		t.Errorf("role = %v, want RoleEmbed", f.Role)
	}
	if f.Name != "_" {
		t.Errorf("name = %q, want _", f.Name)
	}
}

func TestContainers_NonBlankArg(t *testing.T) {
	t.Parallel()

	src := `package test

type DB struct{}

type Container struct {
	DB *DB ` + "`inject:\"arg\"`" + `
}
`
	pkg := loadTestPackage(t, src)
	cs, ds := scan.Containers([]*packages.Package{pkg})
	if diag.HasErrors(ds) {
		t.Fatalf("unexpected error diags: %v", ds)
	}
	if len(cs) != 1 || len(cs[0].Fields) != 1 {
		t.Fatalf("containers/fields shape unexpected: %+v", cs)
	}
	f := cs[0].Fields[0]
	if f.Role != ir.RoleArg {
		t.Errorf("role = %v, want RoleArg", f.Role)
	}
	if f.Name != "DB" {
		t.Errorf("name = %q, want DB", f.Name)
	}
}

func TestContainers_EmbedRequiresBlankField(t *testing.T) {
	t.Parallel()

	src := `package test

type Infra struct{}

type Container struct {
	Infra *Infra ` + "`inject:\"embed\"`" + `
}
`
	pkg := loadTestPackage(t, src)
	_, ds := scan.Containers([]*packages.Package{pkg})
	if !diag.HasErrors(ds) {
		t.Fatalf("expected error diag, got %v", ds)
	}
}

func TestContainers_InvalidTagProducesDiag(t *testing.T) {
	t.Parallel()

	src := `package test

type Bad struct {
	X int ` + "`inject:\"xyz\"`" + `
}
`
	pkg := loadTestPackage(t, src)
	cs, ds := scan.Containers([]*packages.Package{pkg})

	if !diag.HasErrors(ds) {
		t.Fatalf("expected error diag, got %v", ds)
	}
	if len(cs) != 0 {
		t.Errorf("expected no container (only invalid field), got %d", len(cs))
	}
}

func TestContainers_GeneratedFileIgnored(t *testing.T) {
	t.Parallel()

	src := `// Code generated by injector. DO NOT EDIT.

package test

type Container struct {
	User *Container ` + "`inject:\"\"`" + `
}
`
	pkg := loadTestPackage(t, src)
	cs, ds := scan.Containers([]*packages.Package{pkg})

	if diag.HasErrors(ds) {
		t.Fatalf("unexpected error diags: %v", ds)
	}
	if len(cs) != 0 {
		t.Errorf("expected generated file to be ignored, got %d containers", len(cs))
	}
}

// loadTestPackage parses and type-checks a self-contained Go source string,
// returning a *packages.Package suitable for use with the Containers /
// Providers entry points.
func loadTestPackage(t *testing.T, src string) *packages.Package {
	t.Helper()

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "test.go", src, parser.ParseComments)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}

	info := &types.Info{
		Types: make(map[ast.Expr]types.TypeAndValue),
		Defs:  make(map[*ast.Ident]types.Object),
		Uses:  make(map[*ast.Ident]types.Object),
	}
	conf := &types.Config{
		Importer: importer.Default(),
	}
	pkg, err := conf.Check("test", fset, []*ast.File{f}, info)
	if err != nil {
		t.Fatalf("check: %v", err)
	}
	return &packages.Package{
		PkgPath:   "test",
		Name:      "test",
		Syntax:    []*ast.File{f},
		Types:     pkg,
		TypesInfo: info,
		Fset:      fset,
	}
}
