package scan

import (
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"testing"

	"github.com/mickamy/injector/internal/diag"
	"github.com/mickamy/injector/internal/ir"
	"github.com/mickamy/injector/internal/packages"
)

func TestIsGeneratedFile(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		src  string
		want bool
	}{
		{
			name: "canonical marker",
			src:  "// Code generated by injector. DO NOT EDIT.\n\npackage foo\n",
			want: true,
		},
		{
			name: "no marker",
			src:  "// hello\n\npackage foo\n",
			want: false,
		},
		{
			name: "no comments",
			src:  "package foo\n",
			want: false,
		},
		{
			name: "marker after package",
			src:  "package foo\n\n// Code generated by injector. DO NOT EDIT.\n",
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			fset := token.NewFileSet()
			f, err := parser.ParseFile(fset, "test.go", tt.src, parser.ParseComments)
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			if got := isGeneratedFile(f); got != tt.want {
				t.Errorf("isGeneratedFile = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestExtractInjectTag(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		tag        string
		wantInject string
		wantHas    bool
	}{
		{name: "no tag", tag: "", wantHas: false},
		{name: "marker", tag: "`inject:\"\"`", wantHas: true},
		{name: "with", tag: "`inject:\"with=foo.NewBar\"`", wantInject: "with=foo.NewBar", wantHas: true},
		{name: "json only", tag: "`json:\"x\"`", wantHas: false},
		{name: "mixed", tag: "`json:\"x\" inject:\"arg\"`", wantInject: "arg", wantHas: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			var lit *ast.BasicLit
			if tt.tag != "" {
				lit = &ast.BasicLit{Kind: token.STRING, Value: tt.tag}
			}
			_, gotVal, gotHas := extractInjectTag(lit)
			if gotVal != tt.wantInject {
				t.Errorf("inject = %q, want %q", gotVal, tt.wantInject)
			}
			if gotHas != tt.wantHas {
				t.Errorf("has = %v, want %v", gotHas, tt.wantHas)
			}
		})
	}
}

func TestDecideRole(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		field   string
		tag     ParsedTag
		want    ir.Role
		wantErr bool
	}{
		{name: "marker named", field: "Foo", tag: ParsedTag{Kind: TagMarker}, want: ir.RoleOut},
		{name: "marker blank", field: "_", tag: ParsedTag{Kind: TagMarker}, wantErr: true},
		{name: "with named", field: "Foo", tag: ParsedTag{Kind: TagWith, With: "X"}, want: ir.RoleOut},
		{name: "with blank", field: "_", tag: ParsedTag{Kind: TagWith, With: "X"}, want: ir.RoleOverride},
		{name: "arg blank", field: "_", tag: ParsedTag{Kind: TagArg}, want: ir.RoleArg},
		{name: "arg named", field: "Foo", tag: ParsedTag{Kind: TagArg}, wantErr: true},
		{name: "returns named", field: "Foo", tag: ParsedTag{Kind: TagReturns}, want: ir.RoleOut},
		{name: "returns blank", field: "_", tag: ParsedTag{Kind: TagReturns}, want: ir.RoleReturnsOnly},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			role, d := decideRole(tt.field, tt.tag, token.Position{})
			if tt.wantErr {
				if d == nil {
					t.Fatalf("expected error, got role %v", role)
				}
				return
			}
			if d != nil {
				t.Fatalf("unexpected diag: %s", d.Message)
			}
			if role != tt.want {
				t.Errorf("role = %v, want %v", role, tt.want)
			}
		})
	}
}

func TestContainers_Smoke(t *testing.T) {
	t.Parallel()

	src := `package test

type DB struct{}
type User struct{}

type Container struct {
	User *User ` + "`inject:\"\"`" + `
}
`
	pkg := loadTestPackage(t, src)

	cs, ds := Containers([]*packages.Package{pkg})
	if diag.HasErrors(ds) {
		t.Fatalf("unexpected error diags: %v", ds)
	}
	if len(cs) != 1 {
		t.Fatalf("got %d containers, want 1", len(cs))
	}
	c := cs[0]
	if c.StructName != "Container" {
		t.Errorf("StructName = %q", c.StructName)
	}
	if len(c.Fields) != 1 {
		t.Fatalf("fields = %d, want 1", len(c.Fields))
	}
	if got, want := c.Fields[0].Name, "User"; got != want {
		t.Errorf("field name = %q, want %q", got, want)
	}
	if c.Fields[0].Role != ir.RoleOut {
		t.Errorf("role = %v, want RoleOut", c.Fields[0].Role)
	}
}

func TestContainers_AllRolesAndDirective(t *testing.T) {
	t.Parallel()

	src := `package test

type Greeter interface{ Greet() string }
type DB struct{}

//injector:container name=NewApp must
type app struct {
	_   DB      ` + "`inject:\"with=NewWriter\"`" + `
	_   Greeter ` + "`inject:\"arg\"`" + `
	Foo Greeter ` + "`inject:\"returns\"`" + `
}
`
	pkg := loadTestPackage(t, src)
	cs, ds := Containers([]*packages.Package{pkg})

	if diag.HasErrors(ds) {
		t.Fatalf("unexpected error diags: %v", ds)
	}
	if len(cs) != 1 {
		t.Fatalf("containers = %d, want 1", len(cs))
	}

	c := cs[0]
	if c.StructName != "app" {
		t.Errorf("StructName = %q", c.StructName)
	}
	if c.Directive.Name != "NewApp" {
		t.Errorf("Directive.Name = %q, want NewApp", c.Directive.Name)
	}
	if c.Directive.Must != ir.MustOn {
		t.Errorf("Directive.Must = %v, want MustOn", c.Directive.Must)
	}
	if len(c.Fields) != 3 {
		t.Fatalf("fields = %d, want 3", len(c.Fields))
	}

	roles := map[string]ir.Role{}
	hasReturns := map[string]bool{}
	for _, f := range c.Fields {
		roles[f.Name] = f.Role
		hasReturns[f.Name] = f.IsReturns
	}

	if roles["Foo"] != ir.RoleOut {
		t.Errorf("Foo role = %v, want RoleOut", roles["Foo"])
	}
	if !hasReturns["Foo"] {
		t.Errorf("Foo IsReturns = false, want true")
	}

	// 2 blank fields with different tags should both have Name == "_"
	// but distinct roles.
	var argSeen, overrideSeen bool
	for _, f := range c.Fields {
		if f.Name != "_" {
			continue
		}
		switch f.Role {
		case ir.RoleArg:
			argSeen = true
		case ir.RoleOverride:
			overrideSeen = true
			if f.ProviderRef.Raw != "NewWriter" {
				t.Errorf("override ProviderRef = %q, want NewWriter", f.ProviderRef.Raw)
			}
		}
	}
	if !argSeen {
		t.Errorf("RoleArg blank field not found")
	}
	if !overrideSeen {
		t.Errorf("RoleOverride blank field not found")
	}
}

func TestContainers_InvalidTagProducesDiag(t *testing.T) {
	t.Parallel()

	src := `package test

type Bad struct {
	X int ` + "`inject:\"xyz\"`" + `
}
`
	pkg := loadTestPackage(t, src)
	cs, ds := Containers([]*packages.Package{pkg})

	if !diag.HasErrors(ds) {
		t.Fatalf("expected error diag, got %v", ds)
	}
	if len(cs) != 0 {
		t.Errorf("expected no container (only invalid field), got %d", len(cs))
	}
}

func TestContainers_GeneratedFileIgnored(t *testing.T) {
	t.Parallel()

	src := `// Code generated by injector. DO NOT EDIT.

package test

type Container struct {
	User *Container ` + "`inject:\"\"`" + `
}
`
	pkg := loadTestPackage(t, src)
	cs, ds := Containers([]*packages.Package{pkg})

	if diag.HasErrors(ds) {
		t.Fatalf("unexpected error diags: %v", ds)
	}
	if len(cs) != 0 {
		t.Errorf("expected generated file to be ignored, got %d containers", len(cs))
	}
}

// loadTestPackage parses and type-checks a self-contained Go source string,
// returning a *packages.Package suitable for use with the Containers /
// Providers entry points.
func loadTestPackage(t *testing.T, src string) *packages.Package {
	t.Helper()

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "test.go", src, parser.ParseComments)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}

	info := &types.Info{
		Types: make(map[ast.Expr]types.TypeAndValue),
		Defs:  make(map[*ast.Ident]types.Object),
		Uses:  make(map[*ast.Ident]types.Object),
	}
	conf := &types.Config{
		Importer: importer.Default(),
	}
	pkg, err := conf.Check("test", fset, []*ast.File{f}, info)
	if err != nil {
		t.Fatalf("check: %v", err)
	}
	return &packages.Package{
		PkgPath:   "test",
		Name:      "test",
		Syntax:    []*ast.File{f},
		Types:     pkg,
		TypesInfo: info,
		Fset:      fset,
	}
}
