package scan

import (
	"slices"
	"testing"

	"github.com/mickamy/injector/internal/diag"
	"github.com/mickamy/injector/internal/ir"
	"github.com/mickamy/injector/internal/packages"
)

func TestProviders_VariousShapes(t *testing.T) {
	t.Parallel()

	src := `package test

type DB struct{}
type Greeter interface{ Greet() string }

func NewDB() *DB { return nil }
func NewDBWithError() (*DB, error) { return nil, nil }
func NewGreeter() Greeter { return nil }

// Not providers.
func ReturnsString() string { return "" }
func ReturnsErrorOnly() error { return nil }
func TwoResultsNoError() (string, int) { return "", 0 }
func ThreeResults() (*DB, *DB, error) { return nil, nil, nil }
func NoResults() {}

// Methods are not providers.
func (d *DB) NewSelf() *DB { return d }
`
	pkg := loadTestPackage(t, src)
	ps, ds := Providers([]*packages.Package{pkg})

	if diag.HasErrors(ds) {
		t.Fatalf("unexpected error diags: %v", ds)
	}

	got := providerNames(ps)
	slices.Sort(got)
	want := []string{"NewDB", "NewDBWithError", "NewGreeter"}
	if !slices.Equal(got, want) {
		t.Errorf("provider names = %v, want %v", got, want)
	}

	byName := map[string]ir.Provider{}
	for _, p := range ps {
		byName[p.FuncName] = p
	}
	if byName["NewDB"].ReturnsError {
		t.Errorf("NewDB.ReturnsError = true, want false")
	}
	if !byName["NewDBWithError"].ReturnsError {
		t.Errorf("NewDBWithError.ReturnsError = false, want true")
	}
	if byName["NewGreeter"].ReturnsError {
		t.Errorf("NewGreeter.ReturnsError = true, want false")
	}
}

func TestProviders_GeneratedFileIgnored(t *testing.T) {
	t.Parallel()

	src := `// Code generated by injector. DO NOT EDIT.

package test

type DB struct{}

func NewDB() *DB { return nil }
`
	pkg := loadTestPackage(t, src)
	ps, ds := Providers([]*packages.Package{pkg})

	if diag.HasErrors(ds) {
		t.Fatalf("unexpected error diags: %v", ds)
	}
	if len(ps) != 0 {
		t.Errorf("expected generated file to be ignored, got %d providers", len(ps))
	}
}

func TestProviders_RecordsParams(t *testing.T) {
	t.Parallel()

	src := `package test

type DB struct{}
type User struct{}

func NewDB() *DB { return nil }
func NewUser(db *DB, tag string) *User { return nil }
`
	pkg := loadTestPackage(t, src)
	ps, _ := Providers([]*packages.Package{pkg})

	var newUser ir.Provider
	for _, p := range ps {
		if p.FuncName == "NewUser" {
			newUser = p
			break
		}
	}
	if newUser.FuncName == "" {
		t.Fatal("NewUser provider not found")
	}
	if got, want := len(newUser.Params), 2; got != want {
		t.Errorf("NewUser params count = %d, want %d", got, want)
	}
}

func providerNames(ps []ir.Provider) []string {
	out := make([]string, 0, len(ps))
	for _, p := range ps {
		out = append(out, p.FuncName)
	}
	return out
}
