// Code generated by injector. DO NOT EDIT.

package main

import (
	di "github.com/mickamy/injector/example/embedded/di"
	service "github.com/mickamy/injector/example/embedded/service"
)

// NewApp initializes dependencies and constructs App.
func NewApp(infra *di.Infra) *App {
	user := service.NewUser(infra.Database)

	return &App{
		UserService: user,
	}
}
