// Code generated by injector. DO NOT EDIT.

package main

import (
	infra "github.com/mickamy/injector/example/embedded/infra"
	service "github.com/mickamy/injector/example/embedded/service"
)

// NewApp initializes dependencies and constructs App.
func NewApp(database *infra.Database) *App {
	userService := service.NewUser(database)

	return &App{
		UserService: userService,
	}
}
