// Code generated by injector. DO NOT EDIT.

package di

import (
	config "github.com/mickamy/injector/example/embed/config"
	infra "github.com/mickamy/injector/example/embed/infra"
)

// NewInfra initializes dependencies and constructs Infra.
func NewInfra() *Infra {
	databaseConfig := config.NewReaderDatabaseConfig()
	database := infra.NewDatabase(databaseConfig)

	return &Infra{
		Database: database,
	}
}
